# Generated by Django 6.0.5 on 2026-05-26 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Posición',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dorsal', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='futbol.equipo')),
                ('posicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='futbol.posicion')),
            ],
            options={
                'verbose_name': 'Jugador',
                'ordering': ['equipo', 'dorsal'],
            },
        ),
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos', models.IntegerField(default=0)),
                ('goles', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.jugador')),
            ],
            options={
                'verbose_name': 'Alineación',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='futbol.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='futbol.equipo')),
                ('jugadores', models.ManyToManyField(blank=True, through='futbol.Alineacion', to='futbol.jugador')),
            ],
            options={
                'verbose_name': 'Partido',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='alineacion',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.partido'),
        ),
        migrations.CreateModel(
            name='PerfilEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=100)),
                ('entrenador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='futbol.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('min_jugados', models.IntegerField(default=0)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futbol.jugador')),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('jugador', 'fecha'), name='unique_jugador_fecha')],
            },
        ),
        migrations.AddConstraint(
            model_name='alineacion',
            constraint=models.UniqueConstraint(fields=('jugador', 'partido'), name='unique_jugador_partido'),
        ),
    ]
