# Generated by Django 6.0.5 on 2026-05-10 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alineacion',
            options={'verbose_name': 'Alineación'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Equipo'},
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'ordering': ['equipo', 'dorsal'], 'verbose_name': 'Jugador'},
        ),
        migrations.AlterModelOptions(
            name='partido',
            options={'ordering': ['fecha'], 'verbose_name': 'Partido'},
        ),
        migrations.AlterModelOptions(
            name='posicion',
            options={'ordering': ['nombre'], 'verbose_name': 'Posición'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
