# Generated by Django 6.0.5 on 2026-05-10 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0002_alter_alineacion_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='jugadores',
            field=models.ManyToManyField(blank=True, to='futbol.jugador'),
        ),
        migrations.CreateModel(
            name='PerfilEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=100)),
                ('entrenador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='futbol.entrenador')),
            ],
        ),
    ]
