# Generated by Django 6.0.5 on 2026-05-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0003_entrenador_partido_jugadores_perfilentrenador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alineacion',
            old_name='minutos_jugados',
            new_name='minutos',
        ),
    ]
